# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
                ('is_bot', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('real_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tz', models.CharField(blank=True, max_length=50, null=True)),
                ('tz_offset', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('image_192', models.CharField(blank=True, max_length=1024, null=True)),
                ('slack_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.SlackTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.SlackUser')),
                ('slack_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.SlackTeam')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.SlackUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'slack_team')]),
        ),
    ]
