# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='user_id',
            new_name='user',
        ),
    ]
