# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170114_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('anonymous', models.BooleanField(default=True)),
                ('feedback', models.TextField()),
                ('given', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slackuser',
            name='id',
        ),
        migrations.AddField(
            model_name='teammember',
            name='can_see_feedbacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_user', to='teams.SlackUser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipient_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_response', to='teams.Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='teams.SlackUser'),
        ),
    ]
