# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_feedback_response_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_url_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
