# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170114_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='flagged_difficult_to_understand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='flagged_helpful',
            field=models.BooleanField(default=False),
        ),
    ]
