# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_slackuser_image_24'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackuser',
            options={'ordering': ('real_name', 'name')},
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
