# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20170115_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-given',)},
        ),
        migrations.AddField(
            model_name='slackuser',
            name='show_slash_prompt_hint',
            field=models.BooleanField(default=False),
        ),
    ]
