# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_feedbackquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='question',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
