# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_feedback_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='generic_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='team_question',
            field=models.BooleanField(default=False),
        ),
    ]
