# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20170116_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentQuestion',
            fields=[
                ('sent_question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, help_text='Timestamp for answering to this feedback prompt.', null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Timestamp for dismissing this feedback prompt.', null=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Feedback')),
                ('feedback_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_receiver', to='teams.SlackUser')),
                ('feedback_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sender', to='teams.SlackUser')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
