# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20170122_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
